version: '3.8'

services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - bot-network

  wplace-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wplace-worker
    ports:
      - "8888:8888"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge