version: '3.8'

services:
  flaresolverr:
    # docker run --shm-size=2gb -p 8191:8191 my-byparr:latest
    build:
      context: ./byparr
      dockerfile: Dockerfile
    shm_size: 2GB
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Brussels
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - bot-network

  wplace-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wplace-worker
    ports:
      - "8888:8888"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge